#+TITLE: Experiments Report
#+AUTHOR: Marco Minutoli
#+EMAIL: marco.minutoli@pnnl.gov

#+OPTIONS: tex:t toc:nil

* Experimental SetUp

The experiments were run on a Intel Xeon E5645 @ 2.40GHz (12MB cache size)
equipped with 24GB of RAM.  The system is running Fedora 27.  The program was
compiled with GCC 7.3.1 with the "-Ofast" and "-march=native" compiler flag.

Execution times were collected with the performance governor enabled (CPU at
maximum speed).  The execution time, reported in the table in seconds, are the
result of a single run of the program.  The memory usage results were collected
in a successive run with Valgrind's /massif/ tool.

* Data

#+NAME: data
#+CAPTION: Break down of the execution time
#+LABEL: tab:performance
|------------------------+-----------------+-----------------|
| *Phase*                | *Time (x = 25)* | *Time (x = 20)* |
|------------------------+-----------------+-----------------|
| SuffixTree Creation    |         5.30397 |         5.30827 |
| SuffixTree Preparation |         1.46306 |         1.46668 |
| MapReads               |         41.1957 |         61.4111 |
| Output                 |        0.920322 |        0.895578 |
| Total                  |         51.4413 |         71.6376 |

Table [[tab:performance]] show a break down of the execution time for the /Peach/
data set.  With the configuration given in the assignment, only 32797 of the
500000 reads have hits with more than 25 consecutive characters.  Reducing
$x=20$, the number of reads that have hits increases to 49158 while the
execution time increases to 61.4 seconds.  The increment is reasonable because
on average each of those reads requires 3 local alignment procedures.

From the measurement using Valgrind massif, the peak memory consumption of the
program is $2,036,277,008$Bytes.
