#! /usr/bin/env python
# encoding: utf-8

def build(bld):
  bld(features = 'cxx cxxprogram',
      source   = 'ReadMappingTool.cc',
      target   = 'read_mapping_tool',
      use = [ 'project-headers', 'read_mapping', 'BOOST' ])

  bld(features = 'cxx cxxprogram',
      source   = 'SuffixTreeTool.cc',
      target   = 'suffixtree_tool',
      use = [ 'project-headers', 'suffixtree', 'BOOST' ])

  bld(features = 'cxx cxxprogram',
      source   = 'LocalGlobalAlignmentTool.cc',
      target   = 'alignment_tool',
      use = [ 'project-headers', 'sequence_alignment', 'BOOST' ])
