#! /usr/bin/env python
# encoding: utf-8

def build(bld):
  bld(features = 'cxx cxxstlib',
      source = [ 'SequenceFileLexer.l', 'SequenceFileParser.yc',
                 'SequenceFileScanner.cc', 'SequenceAlignmentDriver.cc' ],
      target = 'sequence_alignment',
      includes = '.',
      export_includes = '.',
      use='project-headers')
