#! /usr/bin/env python
# encoding: utf-8

def build(bld):
  bld(features = 'cxx cxxstlib',
      source = [ 'SequenceFileLexer.l', 'SequenceFileParser.yc',
                 'SequenceFileScanner.cc', 'SequenceParserDriver.cc'],
      target = 'sequence_parser',
      includes = '.',
      export_includes = '.',
      use=[ 'project-headers', 'RAPIDJSON'])

  bld(features = 'cxx cxxstlib',
      source = [ 'SequenceAlignmentDriver.cc' ],
      target = 'sequence_alignment',
      includes = '.',
      export_includes = '.',
      use=[ 'project-headers', 'sequence_parser'])

  bld(features = 'cxx cxxstlib',
      source = [ 'SuffixTreeDriver.cc', 'SuffixTree.cc' ],
      target = 'suffixtree',
      includes = '.',
      export_includes = '.',
      use=[ 'project-headers', 'sequence_parser'])
